name: 1-daily-task


on:
  
  #push: # push触发
    #branches: [ main ]
  workflow_dispatch: 
  schedule: 
    - cron: '0 8,16 * * *'
    

jobs:
  daily-task:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]
        node-registry: ['https://registry.npmjs.org']

    steps:
    
    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ matrix.node-registry }}

    - name: Install dependencies
      #if: steps.use-npm-cache.outputs.cache-hit != 'true' || steps.use-npm-depends.outputs.cache-hit != 'true'
      run: npm install
       
    - name: Run daily task
      env:
        user: ${{secrets.unicom_user}}
        password: ${{secrets.unicom_password}}
        appid: ${{secrets.unicom_appid}}
      run: node index.js unicom --user=${user} --password=${password} --appid=${appid}  --tryrun --tasks dailysignin,winterTwo,dxIntegralEveryDay,dailygamebox,dailylotteryintegral,dailycomment,dailywoTree,dailyBookRead,dailyBookRead10doDraw,dailyBookLuckdraw,dailyLiuLan,dailyVideoFreeGoods,dailyGrabdollPage,jflottery,jflotteryad,dailyYYY,dailyVideoScratchcard,dailyLKMH,dailyYYQ,bcow,dailyVideo,dailylottery,gameYearBox,producGameSignin,dailygameflow,dailygameIntegral,todayDailyTask,dailyCourse,ingots,threeSquirrels,freeDownFloorAd,dailyBaWangcard,book5video,dailyFingerqd,dailyFingerqd2,taocan,dailyTurncards,fapiao,fetchCoins
